#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;

namespace SketchEngine.EditorTools.Data
{
    // Sinh file danh sách warmup CHỈ khi build; xóa ngay sau khi build. Editor không có file này.
    public class DataBlockRegistryBuilder : IPreprocessBuildWithReport, IPostprocessBuildWithReport
    {
        const string GeneratedFolderPath = "Assets/SketchEngine/Runtime/Core/Data/Generated";
        const string GeneratedAssetPath = GeneratedFolderPath + "/DataBlockRegistry.g.cs";
        const string DataBlockOpenName = "SketchEngine.Data.DataBlock`1";

        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            Generate();
        }

        public void OnPostprocessBuild(BuildReport report)
        {
            Delete();
        }

        // Build bị lỗi giữa chừng thì postprocess không chạy -> dọn file sót khi mở Editor.
        [InitializeOnLoadMethod]
        static void CleanupStaleFolder()
        {
            if (Directory.Exists(ToSystemPath(GeneratedFolderPath)))
                Delete();
        }

        static void Generate()
        {
            List<string> names = FindBlockTypeNames();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Sinh tự động khi build, không chỉnh tay, không commit.");
            sb.AppendLine("namespace SketchEngine.Data");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class DataBlockWarmup");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void WarmupGenerated()");
            sb.AppendLine("        {");
            sb.AppendLine("            s_generatedRan = true;");

            for (int i = 0; i < names.Count; i++)
                sb.AppendLine($"            global::{names[i]}.Warmup();");

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(ToSystemPath(GeneratedFolderPath));
            File.WriteAllText(ToSystemPath(GeneratedAssetPath), sb.ToString(), Encoding.UTF8);

            AssetDatabase.Refresh();
            AssetDatabase.ImportAsset(GeneratedAssetPath, ImportAssetOptions.ForceSynchronousImport);
        }

        // Xóa cả thư mục (kèm .meta) để không để lại dấu vết nào trong project.
        static void Delete()
        {
            if (Directory.Exists(ToSystemPath(GeneratedFolderPath)))
                AssetDatabase.DeleteAsset(GeneratedFolderPath);

            AssetDatabase.Refresh();
        }

        static List<string> FindBlockTypeNames()
        {
            var names = new List<string>();
            Type openBase = null;

            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            for (int i = 0; i < assemblies.Length; i++)
            {
                openBase = assemblies[i].GetType(DataBlockOpenName);
                if (openBase != null) break;
            }

            if (openBase == null) return names;

            for (int i = 0; i < assemblies.Length; i++)
            {
                Type[] types;
                try
                {
                    types = assemblies[i].GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    types = Array.FindAll(e.Types, t => t != null);
                }

                for (int j = 0; j < types.Length; j++)
                {
                    Type type = types[j];
                    if (!type.IsClass || type.IsAbstract || type.IsGenericTypeDefinition) continue;
                    if (!InheritsDataBlock(type, openBase)) continue;

                    names.Add(type.FullName.Replace('+', '.'));
                }
            }

            return names;
        }

        static bool InheritsDataBlock(Type type, Type openBase)
        {
            Type current = type.BaseType;
            while (current != null)
            {
                if (current.IsGenericType && current.GetGenericTypeDefinition() == openBase)
                    return true;

                current = current.BaseType;
            }

            return false;
        }

        static string ToSystemPath(string assetPath)
        {
            return Path.Combine(Directory.GetParent(UnityEngine.Application.dataPath).FullName, assetPath);
        }
    }
}
#endif
